-- DropForeignKey
ALTER TABLE "IMERCCITLRevision" DROP CONSTRAINT "IMERCCITLRevision_iMFileId_fkey";

-- AddForeignKey
ALTER TABLE "IMERCCITLRevision" ADD CONSTRAINT "IMERCCITLRevision_iMFileId_fkey" FOREIGN KEY ("iMFileId") REFERENCES "IMFile"("id") ON DELETE CASCADE ON UPDATE CASCADE;
