type IMState =
  | "IMERC_CITL_DIRECTOR_ENDORSED"
  | "IMERC_CITL_IDD_COORDINATOR_ENDORSED"
  | "IMERC_CITL_RETURNED_REVISION"
  | "IMERC_CITL_REVISED"
  | "IMERC_CITL_REVIEWED"
  | "IMERC_QAMIS_DEPARTMENT_ENDORSED"
  | "IMERC_QAMIS_REVISED"
  | "IMPLEMENTATION_CITL_DIRECTOR_ENDORSED"
  | "IMPLEMENTATION_CITL_IDD_COORDINATOR_ENDORSED"
  | "IMPLEMENTATION_CITL_RETURNED_REVISION"
  | "IMPLEMENTATION_CITL_REVISED"
  | "IMPLEMENTATION_CITL_REVIEWED"
  | "IMPLEMENTATION_DEPARTMENT_DEAN_ENDORSED"
  | "IMPLEMENTATION_DEPARTMENT_COORDINATOR_ENDORSED"
  | "IMPLEMENTATION_DEPARTMENT_RETURNED_REVISION"
  | "IMPLEMENTATION_DEPARTMENT_REVISED"
  | "IMPLEMENTATION_DEPARTMENT_REVIEWED"
  | "IMPLEMENTATION_DEPARTMENT_REVIEW"
  | "IMPLEMENTATION_DRAFT";

export default IMState;
