// Warning: Changing these values will change previous resources created
// Do not ever delete any question here at any case
// When updating a question, should add versioning for example: 
// for question q1_1, add a new question labeled q1_1_2

const ReviewQuestions = {
    s1: "The Title",
    s2: "The Preface",
    s3: "The Introduction in Every Chapter/Unit",
    s4: "The Learning Outcomes",
    s5: "The Discussion/Presentation of the Concepts",
    s6: "The Examples for the Application of the Concepts",
    s7: "The Exercises/Activities",
    s8: "The Rubrics (if applicable)",
    q1_1: "The title is definite.",
    q1_2: "The title is relevant to the contents of the instructional material.",
    q2_1: "The preface is written by the author/s himself/herself/themselves.",
    q2_2: "It includes reasons for creating the material.",
    q2_3: "It states the importance to the users.",
    q2_4: "It introduces what the material is about.",
    q3_1: "The introduction in every chapter/unit gives the overview of the coverage.",
    q4_1: "The content, activities, and assessment and aligned with the LOs.",
    q4_2: "The learning outcomes (COs and SLOs) are addressed in the instructional material.",
    q4_3: "The learning outcomes are appropriate for the topics covered.",
    q5_1: "The concepts are explicitly discussed.",
    q5_2: "All terms are understandable to the learners.",
    q5_3: "The content is free from gender-bias.",
    q6_1: "Examples are provided to illustrate the concepts discussed.",
    q6_2: "The examples are consistent with the concepts discussed.",
    q6_3: "They relate to real-world situations.",
    q6_4: "They motivate students to participate in the learning process.",
    q6_5: "They illustrate attainment of learning outcomes.",
    q7_1: "The exercises/activities are appropriate for demonstrating the learned concepts.",
    q7_2: "There are provisions that encourage students to work collaboratively.",
    q7_3: "The exercises/activities develop creativity, critical thinking, and problem-solving skills of the students.",
    q7_4: "They encourage students to communicate effectively.",
    q7_5: "They are prepared within the capability of the students.",
    q8_1: "The rubrics are appropriate for the assessment.",
    q8_2: "The rubrics describe the criteria through which the learners’ outputs are rated.",
    q8_3: "The rubrics show the levels of achievements of quality of the assessment outputs.",
}
