const SyllabusReviewQuestions = {
  q1_1: "The course code, course title, credit units, and time duration are indicated.",
  q1_2: "The prerequisite(s) is specified.",
  q1_3: "The course description is clearly stated.",
  q2_1: "The vision, mission, quality policy, institutional outcomes, and core values of the university are accurately stated.",
  q2_2: "The course and specific outcomes describe competencies that are measurable as indicated by specific and active verbs. ",
  q2_3: "The outcomes address the most essential learning competencies.",
  q2_4: "The learning outcomes are student-centered.",
  q2_5: "The learning outcomes are attainable and realistic in a remote learning set-up.",
  q2_6: "The learning outcomes are arranged logically",
  q2_6_1: "Complexity (lowest to the highest level of learning taxonomy)",
  q2_6_2: "Domain (knowledge, skills, values)",
  q3_1: "The Learning Plan specifies the following:",
  q3_1_1: "Schedule",
  q3_1_2: "Course Outcomes",
  q3_1_3: "Specific Learning Outcomes",
  q3_1_4: "Performance Assessment",
  q3_1_5: "Required Readings",
  q3_1_6: "Teacher's Notes",
  q3_2: "The course outcomes are constructively aligned with the specific learning outcomes.",
  q3_3: "The course content fosters self-paced learning.",
  q3_4: "The course outcomes are constructively aligned with the performance assessment tasks/activities.",
  q3_5: "The course content integrates the psychosocial needs of the students during this pandemic.",
  q4_1: "Assessment tools and tasks are performance-based.",
  q4_2: "Assessment tasks are aligned with the course and learning outcomes.",
  q4_3: "Assessment tasks are varied to accommodate learners’ needs.",
  q4_4: "Evaluation/ Grading system is clearly stated.",
  q5_1: "Hybrid flexible teaching and learning modalities are used.",
  q5_2: "Teaching and learning modalities foster inclusivity and equitability.",
  q5_3: "Teaching and learning methods/strategies are relevant to hybrid flexible learning.",
  q5_4: "Teaching and learning methods/strategies are innovative.",
  q5_5: "Teaching and learning methods/strategies emphasize 21st century competencies.",
  q6_1: "Hybrid flexible learning materials are incorporated including classroom-based, offline-online, wired-non-wired, synchronous-asynchronous responsive to the learners.",
  q6_2: "Required readings and references are relevant.",
  q6_3: "References are accessible to the students.",
  q6_4: "References and other resources are of recent edition.",
  q6_5: "The reference list follows the latest edition of the APA.",
  q6_6: "There are five references and 10 e-books/ online resources listed.",
  q7_1: "Policies are responsive to the flexible learning system.",
  q7_2: "Policy on academic integrity is stipulated.",
  q7_3: "Policy identifies the learning management system, communication, and collaborating tools to be used.",
  q7_4: "Policies specify the etiquette in using technology tools and platforms",
  q8_1: "Revision history is indicated.",
  q8_2: "Instructor's name is indicated.",
  q8_3: "The names of the recommending approval are indicated:",
  q8_3_1: "Program Coordinator or Chairperson",
  q8_3_2: "Dean ",
  q8_3_3: "CITL Director",
  q8_3_4: "VPAA",
  q8_4: "The syllabus adheres to the University Document Control standards.",
  q9_1: "Paper size (A4)",
  q9_2: "Paper Orientation (landscape)",
  q9_3: "Line Spacing (single)",
  q9_4: "Margin (1 inch – right, left, top, bottom)",
  q9_5: "Font (Book Antiqua)",
  q9_6: "Headings (12 pt) Text (11 pt) (Except for Page 1 with 9 pt font size)",
};

export default SyllabusReviewQuestions;
