-- DropForeignKey
ALTER TABLE "QAMISRevision" DROP CONSTRAINT "QAMISRevision_iMFileId_fkey";

-- AddForeignKey
ALTER TABLE "QAMISRevision" ADD CONSTRAINT "QAMISRevision_iMFileId_fkey" FOREIGN KEY ("iMFileId") REFERENCES "IMFile"("id") ON DELETE CASCADE ON UPDATE CASCADE;
